import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import Link from "next/link";

import Particle from "@/components/Particle";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [loaded, setLoaded] = useState(false);
  let i = 0;
  let j = 0;
  let intro = "Hello, I'm Sean";
  let title = "A Fullstack Web Developer";
  let speed = 150;
  let visible = styles.visible;
  let navigation = styles.navigation;
  const typeWriter = function () {
    if (i < intro.length) {
      document.getElementById("intro").innerHTML += intro.charAt(i);
      i++;

      setTimeout(typeWriter, speed);
    }
    if (i === intro.length && j < title.length) {
      document.getElementById("title").innerHTML += title.charAt(j);
      j++;
      setTimeout(typeWriter, speed);
    }
    if (i === intro.length && j === title.length) {
      document.getElementById("learn-more").className = visible;
      document.getElementById("navigation").className = navigation;
      setLoaded(true);
    }
  };

  useEffect(() => {
    typeWriter();
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <Head>
        <title>Sean Brown</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.hero}>
          <Particle />
          <nav id="navigation" className={styles.hiddenNav}>
            <div>Logo</div>
            <div>
              <ol className={styles.navLinksList}>
                <li className={styles.navLinksItem}>
                  <Link href="/#main" scroll={false}>
                    About me
                  </Link>
                </li>
                <li className={styles.navLinksItem}>
                  <Link href="/" scroll={false}>
                    Projects
                  </Link>
                </li>
                <li className={styles.navLinksItem} scroll={false}>
                  <Link href="/">Contact</Link>
                </li>
                <li className={styles.resumeBtnItem}>
                  <Link href="/Sean Brown_Resume (2).pdf" target="_blank">
                    <button className={styles.resumeBtn}>Resume</button>
                  </Link>
                </li>
              </ol>
            </div>
          </nav>
          <div className={styles.headerBox}>
            <div className={styles.header}>
              <Image
                className={styles.meImg}
                src="https://www.iconpacks.net/icons/2/free-user-icon-3296-thumb.png"
                width={100}
                height={100}
              />
              <h1 id="intro"></h1>
              <h2 id="title"></h2>
            </div>
            <button
              id="learn-more"
              className={styles.hidden}
              disabled={!loaded ? true : false}
              onClick={() => document.getElementById("main").scrollIntoView()}
            >
              <span className="material-symbols-outlined" id={styles.arrow}>
                south
              </span>
            </button>
          </div>
        </div>
        <div id="main" className={styles.mainContent}>
          <h2>Content</h2>
          <h3>Content</h3>
          <h4>Content</h4>
        </div>
      </main>
    </>
  );
}
